#!/usr/bin/env python3
"""Extract version information from src/version.h into src/version.mk."""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

HEADER_MACROS = {
    "ENGINE_NAME": re.compile(r"#define\s+ENGINE_NAME\s+\"([^\"]*)\""),
    "ENGINE_BUILD_DATE": re.compile(r"#define\s+ENGINE_BUILD_DATE\s+\"([^\"]*)\"")
}


def extract_macros(header_path: pathlib.Path) -> dict[str, str]:
    text = header_path.read_text(encoding="utf-8")
    results: dict[str, str] = {}

    for key, pattern in HEADER_MACROS.items():
        match = pattern.search(text)
        if not match:
            raise SystemExit(f"Unable to find {key} in {header_path}")
        results[key] = match.group(1).strip()

    return results


def write_version_mk(values: dict[str, str], output_path: pathlib.Path) -> None:
    lines = [
        "# This file is generated by scripts/extract_version.py. Do not edit manually.",
        *(f"{key} := {value}" for key, value in values.items()),
        ""
    ]
    output_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--header",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent / "src" / "version.h",
        help="Path to version.h"
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent / "src" / "version.mk",
        help="Path to output Makefile fragment"
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    values = extract_macros(args.header)
    write_version_mk(values, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
